database:
  user:     "_env:PGUSER:qua-kit_LOWER"
  password: "_env:PGPASS:qua-kit"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  # See config/test-settings.yml for an override during tests
  database: "_env:PGDATABASE:qua-kit_LOWER"
  poolsize: "_env:PGPOOLSIZE:10"

